[package]
name = "md4x"
version = "0.1.2"
edition = "2024"
description = "Convert a Markdown file to a magazine-quality PDF."

[dependencies]
anyhow = "1"
clap = { version = "4", features = ["derive"] }
comrak = { version = "0.27", features = ["syntect"] }
chrono = { version = "0.4", default-features = false, features = ["clock"] }
include_dir = "0.7"
two-face = "0.5"

[profile.release]
opt-level = "z"
lto = true
codegen-units = 1
strip = true
panic = "abort"

[lib]
name = "md4x"
path = "src/lib.rs"

[[bin]]
name = "md4x"
path = "src/main.rs"
