[package]
name = "md4x-core"
version.workspace = true
edition.workspace = true

[features]
default = []
bundle-templates = []

[dependencies]
anyhow.workspace = true
comrak.workspace = true
chrono.workspace = true
include_dir.workspace = true
two-face.workspace = true
percent-encoding.workspace = true
serde_json.workspace = true

[lib]
name = "md4x_core"
path = "src/lib.rs"
