[package]
name = "md4x-gui"
version.workspace = true
edition.workspace = true

[dependencies]
md4x-core = { path = "../md4x-core" }
anyhow.workspace = true
serde.workspace = true
serde_json.workspace = true
tauri = { version = "2", features = ["image-png"] }
tauri-plugin-dialog = "2"

[build-dependencies]
tauri-build = { version = "2", features = [] }

[[bin]]
name = "md4x-gui"
path = "src-tauri/main.rs"
